Disable output colorization on terminals that don't support it
knurling-rs/probe-run pull request #318
Opened 2022-04-06 09:31 UTC by fhars

The current version of the colored crate ignores the capabilities of
the terminal (see https://github.com/mackwic/colored/issues/108),
which makes the outupt of probe-run unparseable in e.g. emacs
compilation mode. As a temporary workaround, this patch overrides
colorization if probe-run is called from a terminal without color
support.

2022-04-11 11:59 UTC, Urhengulas requested changes
Hi @fhars, thank you for the patch. I tested it and it seems to work as expected. Can you please add the `Cargo.lock` file as well?

I have two concerns regarding the added `terminfo` dependency:
1. The maintenance of it seems to be currently unclear. See https://github.com/meh/rust-terminfo/issues/20. There are a few people interested in taking over maintenance, but it seems the handover didn't happen yet.
2. It adds outdated versions for a few dependencies, which some of them are already part of our dependency tree. This partially like a symptom of point 1.

*I think* it is reasonable to merge this PR anyways, but we should keep an eye on that and if it stays unmaintained eventually look for an alternative crate.

2022-04-11 12:43 UTC, jonas-schievink commented
Does emacs' compilation mode present itself as a terminal (via `isatty`) to the program (I do hope we support non-isatty mode properly already, so perhaps it doesn't)? Does it set something like `TERM=dumb` that we could detect instead?

2022-04-11 13:47 UTC, Urhengulas commented
> Does emacs' compilation mode present itself as a terminal (via `isatty`) to the program (I do hope we support non-isatty mode properly already, so perhaps it doesn't)? Does it set something like `TERM=dumb` that we could detect instead?

From reading https://github.com/mackwic/colored/issues/108 I understood that it is setting `TERM=dumb`. But I don't know if this is the only trigger we want to look out for, or if there is other ones as well?

2022-04-13 10:52 UTC, Urhengulas commented
@fhars Since it is a temporary fix until `colored` handles it properly, would it be enough for your purposes to only check `TERM=dumb` and disable coloring then?

2022-05-09 13:36 UTC, Urhengulas commented
Superseded by #320

2022-05-09 13:36 UTC, closed without merging