[WIP] add option to verify written flash
knurling-rs/probe-run pull request #353
Opened 2022-09-10 16:43 UTC by Suyash458

- add option to verify written flash
 - fixes #236

2022-09-10 17:05 UTC, Suyash458 commented
@Urhengulas I've got an ST Link JTAG programmer and an ESP32, would love some tips on testing this out!

2022-09-13 09:29 UTC, Urhengulas requested changes
> @Urhengulas I've got an ST Link JTAG programmer and an ESP32, would love some tips on testing this out!

Sure!

1. Install your local `probe-run`
    ```console
    $ cd path/to/probe-run
    $ cargo install --path .
    ```
2. Set up the https://github.com/knurling-rs/app-template for your board
3. Add the `--verify` option to the `runner` in `.cargo/config.toml` ([link](https://github.com/knurling-rs/app-template/blob/main/.cargo/config.toml#L3))
4. Then just run a few of the examples, e.g.:
    ```console
    $ cargo rb hello
    ```
5. Try it in combination with some of the other configuration flags, e.g. `--measure-stack`, `--no-flash`, `--connect-under-reset`
6. If that behaves as expected you can mark the PR as ready for review.

PS: Please add the change to the `CHANGELOG.md`.

2022-09-13 09:29 UTC, Urhengulas commented on src/cli.rs
> +    pub verify: bool,
Please move this before `_rest`.

2022-09-18 17:35 UTC, Suyash458 commented
> > @Urhengulas I've got an ST Link JTAG programmer and an ESP32, would love some tips on testing this out!
> 
> Sure!
> 
> 1. Install your local `probe-run`
>    ```
>    $ cd path/to/probe-run
>    $ cargo install --path .
>    ```
> 2. Set up the https://github.com/knurling-rs/app-template for your board
> 3. Add the `--verify` option to the `runner` in `.cargo/config.toml` ([link](https://github.com/knurling-rs/app-template/blob/main/.cargo/config.toml#L3))
> 4. Then just run a few of the examples, e.g.:
>    ```
>    $ cargo rb hello
>    ```
> 5. Try it in combination with some of the other configuration flags, e.g. `--measure-stack`, `--no-flash`, `--connect-under-reset`
> 6. If that behaves as expected you can mark the PR as ready for review.
> 
> PS: Please add the change to the `CHANGELOG.md`.

@Urhengulas Turns out the ST Link debuggers don't work with the ESP32 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/index.html#jtag-debugging-selecting-jtag-adapter

Would it be possible to test this out on your end?

2022-09-19 11:46 UTC, Urhengulas requested changes
I tested it and it seems to verify it. At least the `probe-rs` logs say so.

Looking into the code I realized that the `--verify` option would be skipped, if used together with `--no-flash`. Can you therefore please change the attribute of `no_flash` (not `verify`!) to following:
```diff
/// Skip writing the application binary to flash.
-    #[structopt(long, conflicts_with = "defmt")]
+    #[structopt(
+        long,
+        conflicts_with = "disable-double-buffering",
+        conflicts_with = "verify"
+    )]
    pub no_flash: bool,
```
(`defmt` isn't needed anymore, and `disable-double-buffering` has no effect with `--no-flash` as well)

Other than that it looks good to me!

2022-09-19 16:32 UTC, Urhengulas commented
bors r+

2022-09-20 09:32 UTC, Urhengulas requested changes
Can you please run `cargo fmt`?
Afterwards you can use `bors r+` to merge.

bors d+

2022-09-28 19:13 UTC, Suyash458 commented
bors r+

2022-09-28 19:20 UTC, merged